config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'
  get 'sessions/new'
  root 'pages#top'
  
  get '/index', to: 'pages#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :topics
  
  get 'search', to: 'topics#search'
  post "topics/:id/destroy" => "topics#destroy"
  
  get 'boards/index'
  get 'boards/show/:id' => 'boards#show', as: :boards_show
  post 'boards/create' => 'boards#create'
  delete 'boards/delete/:id' => 'boards#delete', as: :boards_delete
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
 
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
  mount_uploader :image, ImageUploader
  
  #検索機能
  def self.search(search)
    return Topic.all unless search
    Topic.where(['class_name LIKE ?',"%#{search}%"])
  end
  
  #Topicを降順に
  default_scope -> { order(created_at: :desc) }
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password,presence: true
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
   
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
    @newboard = Board.new
  end

  def show
  end
  
  def create
    @board = Board.new(params[:board].permit(:title))
    @board.save
    redirect_to boards_index_path
  end
  
  def delete
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_index_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入り登録に失敗しました'
    end
  end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    favorite.destroy

    if favorite.destroy
      redirect_to topics_path, success: 'お気に入りを解除しました'
    else
      redirect_to topics_path, danger: 'お気に入りの解除に失敗しました'
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def top
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
   user = User.find_by(user_params)
   if user && user.authenticate(params[:session][:password])
     log_in user
     redirect_to topics_path, success: 'ログインに成功しました'
   else
     flash.now[:danger] = 'ログインに失敗しました'
     render :new
   end
  end
  
   def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
   end
   
   private
   def log_out
    session.delete(:user_id)
    @current_user = nil
   end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def user_params
    params.require(:session).permit(:name, :email)
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @q = Topic.ransack(params[:q])
    @Topics = @q.result.includes(:class_name)
    
    @topics = Topic.all.includes(:favorite_users)
    @topics = Topic.page(params[:page]).per(6)
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def edit
    @topic = Topic.find_by(id: params[:id])
  end
  
  def update
    @topic = Topic.find_by(id: params[:id])
    if @topic.update_attributes(topic_params)
      redirect_to topics_path, success: "編集しました"
    else
      flash.now[:danger] = "編集できませんでした"
      render :edit
    end
  end
  
  def search
    @q = Topic.ransack(params[:q])
    @topics = @q.result
  end
  
  def destroy
    @topic = Topic.find_by(id: params[:id])
    @topic.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to(topics_path)
  end
  
  private
  def topic_params
    params.require(:topic).permit(:description, :year, :class_name, :class_teacher, :semester, :week, :term, :satisfaction, :difficulty_level, :assessment)
  end
  
  private
  def search_params
    params.require(:q).permit!
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user =User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER = 9
  
  def index
    @pages = Topic.page(params[:page]).per(PER)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/index.html.erb
<h1>掲示板</h1>
<ul>
  <% @boards.each do |board| %>
    <li>
      <%= link_to board.title, boards_show_path(board.id) %>
      <%= link_to '[削除]', boards_delete_path(board.id), method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
    </li>
  <% end %>
</ul>

<h1>スレッド追加</h1>
<%= form_for @newboard, :url => {:action => 'create' } do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<h1>Boards#show</h1>
<p>Find me in app/views/boards/show.html.erb</p>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <div class="row">
      <% @favorite_topics.each do |topic| %>
         <div class="col-md-6">
          <div class="topic-index-single">
            
            
          <!--タイトル--!>
            <h3 class="topic-author">
              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                  <span class="topic-index-icon">
                    <i class="far fa-bookmark"></i>
                  </span>
                <% end %>
              <% else %>
                <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                  <span class="topic-index-icon"><i class="fas fa-bookmark"></i></span>
                <% end %>
              <% end %>
              
              <%= topic.class_name %>
            </h3>
          <!--タイトル終わり--!>
           
          <!--詳細リスト--!>
            <div class="show-item">
            <ul>
              <li class="topic-text ">
                【担当教員名】<%= topic.class_teacher %>
              </li>
              <li class="topic-text ">
                【受講時期】<%= topic.year %>/<%= topic.semester %>
               </li>
              <li class="topic-text ">
                【時限】<%= topic.week %>/<%= topic.term %>
              </li>
              <li class="topic-text">
                【授業充実度】<%= topic.satisfaction %>
              </li>
              <li class="topic-text">
                【単位取得度】<%= topic.difficulty_level %>
              </li>
              <li class="topic-text">
                【主な評価方法】<%= topic.assessment %>
              </li>
              <li class="topic-text">
                【受講する人へのアドバイス】<br><%= topic.description %>
              </li>
            </ul>
            </div>
            <!--詳細リスト終わり--!>
              
            <!--編集削除ボタン追加--!>
              <div class="col-md-offset-9 col-md-3">
                <% if logged_in? && current_user.id == topic.user.id %>
                  <%= link_to edit_topic_path(topic) do %>
                    <span class="topic-index-icon">
                      <i class="fas fa-edit"></i>
                    </span>
                  <% end %>
            
                <%= link_to topic_path(topic), method: :delete do %>
                  <span class="topic-index-icon">
                    <i class="fas fa-trash-alt "></i>
                  </span>
                <%  end %>
              <% end %>
            </div>
            <!--編集削除ボタン終わり--!>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">投稿編集</h1>
        <%= form_for @topic do |f| %>

          <div class="form-group">
            <%= f.label :class_name %>
            <%= f.text_field :class_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :class_teacher %>
            <%= f.text_field :class_teacher, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :year %>
            <%= f.select :year, [["2019年度", "2019年度"], ["2018年度", "2018年度"], ["2017年度", "2017年度"], ["2016年度", "2016年度"], ["その他", "その他"]] ,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :semester %>
            <%= f.select :semester, [["前期", "前期"], ["後期", "後期"]] ,class:"form-control" %>
          </div>
           
          <div class="form-group">
            <%= f.label :week %>
            <%= f.select :week, [["月", "月"], ["火", "火"], ["水", "水"], ["木", "木"], ["金", "金"], ["その他", "その他"]] ,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :term %>
            <%= f.select :term, [["1限", "1限"], ["2限", "2限"], ["3限", "3限"], ["4限", "4限"], ["5限", "5限"], ["その他", "その他"]] ,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :satisfaction %>
            <%= f.select :satisfaction, [["充実してない", "1"], ["あまり充実してない", "2"], ["普通", "3"], ["充実している", "4"], ["とても充実している", "5"]] ,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :difficulty_level %>
            <%= f.select :difficulty_level, [["すごくとりにくい", "1"], ["とりにくい", "2"], ["普通", "3"], ["とりやすい", "4"], ["すごくとりやすい", "5"]] ,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :assessment %>
            <%= f.select :assessment, [["テスト", "テスト"], ["レポート", "レポート"], ["出席", "出席"], ["その他", "その他"]] ,class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <%= f.submit '投稿', class: 'btn btn-block btn-black' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    
    <!--検索機能--!>
    
    <div class="panel row">
      <div class="panel-heading">
        <h3>検索項目</h3>
      </div>
      <div class="panel-body  ">
        <%= search_form_for(@q, url:search_path) do |f| %>
      <div class="form-group col-md-6">
        <%= f.label :class_name_cont, "授業名" %>
        <%= f.search_field :class_name_cont, class:'form-control'%>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :class_teacher_cont, "講師名" %>
        <%= f.search_field :class_teacher_cont, class:'form-control'%>
      </div>
      <div class="form-group col-md-3">
      <%= f.select :year_eq, [["2019年度", "2019年度"], ["2018年度", "2018年度"], ["2017年度", "2017年度"], ["2016年度", "2016年度"], ["その他", "その他"]],{:include_blank => '年度'},{class:'form-control'}%>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :semester_eq, [["前期", "前期"], ["後期", "後期"]], {:include_blank => '学期'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :week_eq, [["月", "月曜"], ["火", "火曜"], ["水", "水曜"], ["木", "木曜"], ["金", "金曜"]] , {:include_blank => '曜日'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :term_eq, [["1限", "1限"], ["2限", "2限"], ["3限", "3限"], ["4限", "4限"], ["5限", "5限"], ["その他", "その他"]] , {:include_blank => '時限'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :satisfaction_eq, [["充実してない", "1"], ["あまり充実してない", "2"], ["普通", "3"], ["充実している", "4"], ["とても充実している", "5"]] , {:include_blank => '授業充実度'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :difficulty_level, [["すごくとりにくい", "1"], ["とりにくい", "2"], ["普通", "3"], ["とりやすい", "4"], ["すごくとりやすい", "5"]] , {:include_blank => '単位取得度'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
         <%= f.select :assessment_eq, [["テスト", "テスト"], ["レポート", "レポート"], ["出席", "出席"], ["その他", "その他"]] , {:include_blank => '主な評価方法'}, {class:'form-control'} %>
      </div>
          
      <div class=" col-md-3 ">
        <%= f.submit '検索', class: ' btn btn-block btn-danger'%>
      </div>
    <% end %>
      </div>
    </div>
    
    
    
    <!--検索機能終わり--!>
    
    
    <div class="row">
      <% @topics.each do |topic| %>
        <div class="col-md-6 ">
          <div class="topic-index-single">
          
          <!--タイトル初め--!>
          <h3 class="topic-author">
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <span class="topic-index-icon">
                  <i class="far fa-bookmark"></i>
                 </span>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                 <span class="topic-index-icon"><i class="fas fa-bookmark"></i></span>
               <% end %>
            <% end %>
             
            <%= topic.class_name %>
            </h3>
            <!--タイトル終わり--!>
          
           
            <!--詳細リストはじめ--!>
            <div class="show-item">
            <ul>
            <li class="topic-text ">
              【担当教員名】<%= topic.class_teacher %>
            </li>
            <li class="topic-text ">
               【受講時期】<%= topic.year %>/<%= topic.semester %>
            </li>
            <li class="topic-text ">
              【時限】<%= topic.week %>/<%= topic.term %>
            </li>
            <li class="topic-text">
              【授業充実度】<%= topic.satisfaction %>
            </li>
            <li class="topic-text">
              【単位取得度】<%= topic.difficulty_level %>
            </li>
            <li class="topic-text">
              【主な評価方法】<%= topic.assessment %>
            </li>
            <li class="topic-text">
              【受講する人へのアドバイス】<br><%= topic.description %>
            </li>
            </ul>
            </div>
            <!--詳細リスト終わり!>
            
            <!--編集削除ボタン追加--!>
            <div class="col-md-offset-9 col-md-3">
              <% if logged_in? && current_user.id == topic.user.id %>
                <%= link_to edit_topic_path(topic) do %>
                  <span class="topic-index-icon">
                    <i class="fas fa-edit"></i>
                  </span>
                <% end %>
            
                <%= link_to topic_path(topic), method: :delete do %>
                  <span class="topic-index-icon">
                    <i class="fas fa-trash-alt"></i>
                  </span>
                <% end %>
              <% end %>
            </div>
            <!--編集削除ボタン終わり--!>
          </div>
        </div>
      <% end %>
    </div>
    
    <!--ページネーション追加--!>
    <div class="row">
      <div class="pagenate col-md-4 col-md-offset 4">
        <%= paginate @topics %>
      </div>
    </div>
    <!--ページネーション終わり--!>
    
    
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">新規投稿</h1>
        <%= form_for @topic do |f| %>

          <div class="form-group">
            <%= f.label :授業名 %>
            <%= f.text_field :class_name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :講師 %>
            <%= f.text_field :class_teacher, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :年度 %>
            <%= f.select :year, [["2019年度", "2019年度"], ["2018年度", "2018年度"], ["2017年度", "2017年度"], ["2016年度", "2016年度"], ["その他", "その他"]],{},{class:'form-control'} %>
          </div>
          <div class="form-group">
            <%= f.label :学期 %>
            <%= f.select :semester, [["前期", "前期"], ["後期", "後期"]] ,{},{class:"form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :曜日 %>
            <%= f.select :week, [["月", "月曜"], ["火", "火曜"], ["水", "水曜"], ["木", "木曜"], ["金", "金曜"]] ,{},{class:"form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :時限 %>
            <%= f.select :term, [["1限", "1限"], ["2限", "2限"], ["3限", "3限"], ["4限", "4限"], ["5限", "5限"], ["その他", "その他"]] ,{},{class:"form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :授業充実度 %>
            <%= f.select :satisfaction, [["充実してない", "1"], ["あまり充実してない", "2"], ["普通", "3"], ["充実している", "4"], ["とても充実している", "5"]] ,{},{class:"form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :単位取得度 %>
            <%= f.select :difficulty_level, [["すごくとりにくい", "1"], ["とりにくい", "2"], ["普通", "3"], ["とりやすい", "4"], ["すごくとりやすい", "5"]] ,{},{class:"form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :主な評価方法 %>
            <%= f.select :assessment, [["テスト", "テスト"], ["レポート", "レポート"], ["出席", "出席"], ["その他", "その他"]], {},{class:"form-control"} %>
          </div>
          <div class="form-group">
            <%= f.label :コメント %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <%= f.submit '投稿', class: 'btn btn-block btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/search.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    
    <!--検索機能--!>
    
    <div class="panel row">
      <div class="panel-heading">
        <h3>検索項目</h3>
      </div>
      <div class="panel-body  ">
        <%= search_form_for(@q, url:search_path) do |f| %>
      <div class="form-group col-md-6">
        <%= f.label :class_name_cont, "授業名" %>
        <%= f.search_field :class_name_cont, class:'form-control'%>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :class_teacher_cont, "講師名" %>
        <%= f.search_field :class_teacher_cont, class:'form-control'%>
      </div>
      <div class="form-group col-md-3">
      <%= f.select :year_eq, [["2019年度", "2019年度"], ["2018年度", "2018年度"], ["2017年度", "2017年度"], ["2016年度", "2016年度"], ["その他", "その他"]],{:include_blank => '年度'},{class:'form-control'}%>
      </div>
      <div class="form-group col-md-3">

        <%= f.select :semester_eq, [["前期", "前期"], ["後期", "後期"]], {:include_blank => '学期'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :week_eq, [["月", "月曜"], ["火", "火曜"], ["水", "水曜"], ["木", "木曜"], ["金", "金曜"]] , {:include_blank => '曜日'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :term_eq, [["1限", "1限"], ["2限", "2限"], ["3限", "3限"], ["4限", "4限"], ["5限", "5限"], ["その他", "その他"]] , {:include_blank => '時限'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :satisfaction_eq, [["充実してない", "1"], ["あまり充実してない", "2"], ["普通", "3"], ["充実している", "4"], ["とても充実している", "5"]] , {:include_blank => '授業充実度'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
        <%= f.select :difficulty_level, [["すごくとりにくい", "1"], ["とりにくい", "2"], ["普通", "3"], ["とりやすい", "4"], ["すごくとりやすい", "5"]] , {:include_blank => '単位取得度'}, {class:'form-control'} %>
      </div>
      <div class="form-group col-md-3">
         <%= f.select :assessment_eq, [["テスト", "テスト"], ["レポート", "レポート"], ["出席", "出席"], ["その他", "その他"]] , {:include_blank => '主な評価方法'}, {class:'form-control'} %>
       </div>
          
      <div class=" col-md-3 ">
        <%= f.submit '検索', class: ' btn btn-block btn-danger'%>
      </div>
    <% end %>
      </div>
    </div>
    
    <!--検索機能終わり--!>
    
    <div class="row">
      <% @topics.each do |topic| %>
        <div class="col-md-6 col-md-offset">
          <div class="topic-index-single">
          
          <!--タイトル初め--!>
          <h3 class="topic-author">
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <span class="topic-index-icon">
                  <i class="far fa-bookmark"></i>
                 </span>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                 <span class="topic-index-icon"><i class="fas fa-bookmark"></i></span>
               <% end %>
            <% end %>
             
            <%= topic.class_name %>
            </h3>
            <!--タイトル終わり--!>
          
           
            <!--詳細リストはじめ--!>
            <div class="show-item">
            <ul>
            <li class="topic-text ">
              【担当教員名】<%= topic.class_teacher %>
            </li>
            <li class="topic-text ">
               【受講時期】<%= topic.year %>/<%= topic.semester %>
            </li>
            <li class="topic-text ">
              【時限】<%= topic.week %>/<%= topic.term %>
            </li>
            <li class="topic-text">
              【授業充実度】<%= topic.satisfaction %>
            </li>
            <li class="topic-text">
              【単位取得度】<%= topic.difficulty_level %>
            </li>
            <li class="topic-text">
              【主な評価方法】<%= topic.assessment %>
            </li>
            <li class="topic-text">
              【受講する人へのアドバイス】<br><%= topic.description %>
            </li>
            </ul>
           </div>
           <!--詳細リスト終わり!>
            
          <!--編集削除ボタン追加--!>
          <div class="col-md-offset-9 col-md-3">
            <% if logged_in? && current_user.id == topic.user.id %>
              <%= link_to edit_topic_path(topic) do %>
                <span class="topic-index-icon">
                  <i class="fas fa-edit"></i>
              </span>
              <% end %>
            
              <%= link_to topic_path(topic), method: :delete do %>
                <span class="topic-index-icon">
                  <i class="fas fa-trash-alt"></i>
                </span>
              <% end %>
            <% end %>
          </div>.
          <!--編集削除ボタン終わり--!>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center">新規登録</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <%= f.submit "登録", class: 'btn btn-block btn-danger' %>
        <% end %>
        <%= link_to 'ログインはこちら',  login_path, class: 'text-info' %>
      </div>
    </div>
  </div>
</div>