config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'
  get 'sessions/new'
  root 'pages#top'
  
  get '/index', to: 'pages#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :topics
  
  get 'search', to: 'topics#search'
  post "topics/:id/destroy" => "topics#destroy"
  
  get 'boards/index'
  get 'boards/show/:id' => 'boards#show', as: :boards_show
  post 'boards/create' => 'boards#create'
  delete 'boards/delete/:id' => 'boards#delete', as: :boards_delete
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
 
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
  mount_uploader :image, ImageUploader
  
  #検索機能
  def self.search(search)
    return Topic.all unless search
    Topic.where(['class_name LIKE ?',"%#{search}%"])
  end
  
  #Topicを降順に
  default_scope -> { order(created_at: :desc) }
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password,presence: true
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
    @newboard = Board.new
  end

  def show
  end
  
  def create
    @board = Board.new(params[:board].permit(:title))
    @board.save
    redirect_to boards_index_path
  end
  
  def delete
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_index_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入り登録に失敗しました'
    end
  end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    favorite.destroy

    if favorite.destroy
      redirect_to topics_path, success: 'お気に入りを解除しました'
    else
      redirect_to topics_path, danger: 'お気に入りの解除に失敗しました'
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def top
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
   user = User.find_by(user_params)
   if user && user.authenticate(params[:session][:password])
     log_in user
     redirect_to topics_path, success: 'ログインに成功しました'
   else
     flash.now[:danger] = 'ログインに失敗しました'
     render :new
   end
  end
  
   def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
   end
   
   private
   def log_out
    session.delete(:user_id)
    @current_user = nil
   end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def user_params
    params.require(:session).permit(:name, :email)
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @q = Topic.ransack(params[:q])
    @Topics = @q.result.includes(:class_name)
    
    @topics = Topic.all.includes(:favorite_users)
    @topics = Topic.page(params[:page]).per(6)
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def edit
    @topic = Topic.find_by(id: params[:id])
  end
  
  def update
    @topic = Topic.find_by(id: params[:id])
    if @topic.update_attributes(topic_params)
      redirect_to topics_path, success: "編集しました"
    else
      flash.now[:danger] = "編集できませんでした"
      render :edit
    end
  end
  
  def search
    @q = Topic.ransack(params[:q])
    @topics = @q.result
  end
  
  def destroy
    @topic = Topic.find_by(id: params[:id])
    @topic.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to(topics_path)
  end
  
  private
  def topic_params
    params.require(:topic).permit(:description, :year, :class_name, :class_teacher, :semester, :week, :term, :satisfaction, :difficulty_level, :assessment)
  end
  
  private
  def search_params
    params.require(:q).permit!
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user =User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER = 9
  
  def index
    @pages = Topic.page(params[:page]).per(PER)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wakamon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-expand-sm navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
        <span class="navbar-brand">wakamon</span>
        <% end %>
        
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
      <span class="sr-only">メニュー</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
        
      <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in?%>
              <li class="nav-item　text-center">
                <%= link_to topics_path do %>
                  <span class="nav-link">投稿一覧</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_topic_path do %>
                  <span class="nav-link">新規投稿</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to favorites_index_path do %>
                  <span class="nav-link">お気に入り</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to logout_path, method: :delete do %>
                  <span class="nav-link">ログアウト</span>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_path do %>
                  <span class="nav-link">新規登録</span>
                <% end %>
              </li class="nav-item">
              <li>
                <%= link_to login_path do %>
                  <span class="nav-link">ログイン</span>
                <% end %>
              </li>
    
            <% end %>
          </ul>
      </div>

      </div>
    </nav>

    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(3000);
      });
    </script>

  </body>
</html>

app/views/pages/top.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Wakamon</h1>
    <h2 class="text-white">和歌山大学の授業情報を共有・閲覧できるサービス</h2>
    <h2></h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to '新規登録',new_user_path, class: 'btn btn-block btn-danger' %>
      </div>     
      <div class="col-md-3">
        <%= link_to 'ログイン', login_path, class: 'btn btn-block btn-success' %>
      </div>
      <div class="col-md-offset-4 col-md-4">
        <%= form_for(:session, url: login_path) do |f| %>
          <%= f.hidden_field :email, value: 'test@example.com' %>
          <%= f.hidden_field :password, value: 'test' %>
          <%= f.submit 'ポートフォリオ閲覧用簡単ログイン', class: 'btn btn-block btn-info' %>
        <% end %>
      </div>
    </div>
  </div>  
</div>